---
title: "madgetech - apply calibrated values to deployment data"
author: "Amelia Ritger"
date: "2022-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load libraries, set constants
```{r}
library(tidyverse)
library(readr)
library(janitor)
library(here)
library(lubridate)

filename_raw <- "1215_deploy_madge"
filename_tris <- "1215_tris_madge"
start_time <-  "12-15-2022 13:30:00" #to remove
end_time <- "12-16-2022 13:15:00" #to remove

# ggplot(raw_calibrated_ideal, aes(x=date_time, y=durafet_temp)) +
#   geom_point()
```

## Run "Ideal" calibration for Madgetech deployment data
```{r}
#load calibration data
calibration_values <- read_csv(here("data", "calibrated", paste(filename_tris,"_omegas_calib.csv",sep=""))) # read in tris data excel file

rawdata <- read_csv(here("data", "raw", paste(filename_raw,".csv",sep=""))) %>% # read in tris data excel file
  filter(row_number()!=c(1:5)) %>% # remove the first 5 rows
  row_to_names(row_number=1) %>% # make the top row the column headers
  rename("Date"=1,
         "Time"=2) %>% # rename date and time columns
  clean_names() %>% # clean up column header names
  mutate(date_lubridate=mdy(date)) %>% # tell R "date" is a DATE
  mutate(time_lubridate=hms(time)) %>% # tell R "time" is a TIME
  unite(date_time, c(date, time), sep = " ", remove = TRUE) %>% # combine the date and time columns
  mutate(date_time_lubridate=mdy_hms(date_time)) %>% # tell R "date_time" is a DATE and a TIME
  arrange(date_time_lubridate) %>%
  filter(date_time_lubridate >= mdy_hms(start_time),
         date_time_lubridate <= mdy_hms(end_time)) 
  
raw_voltages <- data.frame(rawdata$voltage_1_m_v,rawdata$voltage_2_m_v,rawdata$voltage_3_m_v,rawdata$voltage_4_m_v) %>% # create OMEGAS data frame with the raw voltages
  mutate(mv1=as.numeric(rawdata.voltage_1_m_v),
         mv2=as.numeric(rawdata.voltage_2_m_v),
         mv3=as.numeric(rawdata.voltage_3_m_v),
         mv4=as.numeric(rawdata.voltage_4_m_v)) %>% # changing data to numeric arguments
  select(mv1, mv2, mv3, mv4) # cleaning data frame

omegas_temp_raw <- raw_voltages %>% # create OMEGAS data frame with the raw voltages
  mutate(v1=(mv1/1000),
         v2=(mv2/1000),
         v3=(mv3/1000),
         v4=(mv4/1000)) %>% # converting the mV to volts
  mutate(vbattery=((v2/100)*101.57)) %>% # calculate vbattery
  mutate(z=(v4/100)+vbattery*((15000*1)/((1000000*1)+(15000*1)))) %>% # calculate column k
  mutate(y=(z*(1000000*1))) %>% # calculate column l
  mutate(rthermistor=(y/(vbattery-z))) %>% # calculate Rthermistor
  mutate(sh_a=as.numeric(0.00106329736674527)) %>% # create column with Steinhart constant A
  mutate(sh_b=as.numeric(0.000251377462346306)) %>% # create column with Steinhart constant B
  mutate(sh_c=as.numeric(2.55455247726963E-08)) %>% # create column with Steinhart constant C
  mutate(k=(1/(sh_a+sh_b*log(rthermistor)+sh_c*(log(rthermistor))^3))) %>% # create column to calculate intermediate value K
  mutate(durafet=as.numeric((k-273.15))) %>% # create new column to calculate durafet therm 
  mutate(calt=as.numeric(1.0086*durafet+0.3157)) # create Cal_T column (does not get used for further calibration)

temp <- c(omegas_temp_raw$durafet) # copy durafet therm into tris pH template
b <- as.numeric(rep("11911.08",length(temp))) # create vector for tris pH template column b
c <- as.numeric(rep("18.2499",length(temp))) # create vector for tris pH template column c
d <- as.numeric(rep("0.039336",length(temp))) # create vector for tris pH template column d
e <- as.numeric(rep("366.27059",length(temp))) # create vector for tris pH template column e
f <- as.numeric(rep("0.53993607",length(temp))) # create vector for tris pH template column f
g <- as.numeric(rep("0.00016329",length(temp))) # create vector for tris pH template column g
h <- as.numeric(rep("64.52243",length(temp))) # create vector for tris pH template column h
i <- as.numeric(rep("0.084041",length(temp))) # create vector for tris pH template column i
j <- as.numeric(rep("0.11149858",length(temp))) # create vector for tris pH template column j
k <- as.numeric(rep("273.15",length(temp))) # create vector for tris pH template column k
t <- as.numeric(rep(k+temp),length(temp)) # create vector for tris pH template column t
m <- as.numeric(rep("35",length(temp))) # create vector for tris pH template column m

raw_tris_ph <- data.frame(temp,b,c,d,e,f,g,h,i,j,t,k,m) %>% # create tris pH template as a data frame with all above columns
  mutate(n=(b-(c*m)-(d*m*m))*1/t) %>% # create column n
  mutate(o=(-e+(f*m)+(g*m*m))) %>% # create column o
  mutate(p=(h-(i*m))*log(t)-(j*(t))) %>% # create column p
  mutate(trisph=(n+o+p)) # calculate tris pH, add as a new column to tris pH template data frame

omegas_ph_raw <- data.frame(rawdata$date_lubridate,rawdata$time_lubridate,rawdata$date_time_lubridate,omegas_temp_raw$durafet,omegas_temp_raw$v1) %>% # create data frame with durafet therm and voltage 1 values
  rename(date_time=rawdata.date_time_lubridate,
         date=rawdata.date_lubridate,
         time=rawdata.time_lubridate) %>% # rename date/time column from trisdata data frame
  mutate(trisph=raw_tris_ph$trisph) %>% # add tris pH values into calibration dataframe TRIS PH IS NOT THE SAME LENGTH AS THE RAW DATA
  mutate(tk=omegas_temp_raw$durafet+273.15) %>% # add TK column to data frame
  mutate(st=(8.31451*tk/96487*log(10))) %>% # add S(T) column to data frame
  mutate(eo=((calibration_values$v1)-(calibration_values$trisph)*8.31451*(273.15+calibration_values$durafet_temp)*log(10)/96487)) %>% # calculate eo value using calibration values
  mutate(eot=(eo-(0.001*(tk-(273.15+calibration_values$durafet_temp))))) %>% # add Eo(T) column to data frame
  mutate(omegasrawph=(omegas_temp_raw$v1-eot)/st) %>% # add pH column to data frame
  mutate(diff=(trisph-omegasrawph)) # add difference column (tris pH - omegas pH) to data frame

raw_calibrated <- omegas_ph_raw %>% # create new dataframe using omegasph_raw data
  select(date_time, omegas_temp_raw.durafet, omegasrawph) %>% # keep only date/time, temperature, and pH columns
  rename("durafet_temp"=2,
         "p_h"=3)

#unique identifier for final calibrated data
raw_calibrated_ideal <- raw_calibrated %>%
  mutate(logger = "madgetech",
         tolerance = "ideal")

#Write .csv
write.csv(raw_calibrated_ideal, here("data", "calibrated", paste(filename_raw,"_omegas.csv", sep="")),row.names = FALSE) # create csv with calibrated values
```


## Run +1 tolerance calibration for Madgetech deployment data
```{r}
#load calibration data
calibration_values <- read_csv(here("data", "calibrated", paste(filename_tris,"_omegas_plus1_calib.csv",sep=""))) # read in tris data excel file

rawdata <- read_csv(here("data", "raw", paste(filename_raw,".csv",sep=""))) %>% # read in tris data excel file
  filter(row_number()!=c(1:5)) %>% # remove the first 5 rows
  row_to_names(row_number=1) %>% # make the top row the column headers
  rename("Date"=1,
         "Time"=2) %>% # rename date and time columns
  clean_names() %>% # clean up column header names
  mutate(date_lubridate=mdy(date)) %>% # tell R "date" is a DATE
  mutate(time_lubridate=hms(time)) %>% # tell R "time" is a TIME
  unite(date_time, c(date, time), sep = " ", remove = TRUE) %>% # combine the date and time columns
  mutate(date_time_lubridate=mdy_hms(date_time)) %>% # tell R "date_time" is a DATE and a TIME
  arrange(date_time_lubridate) %>%
  filter(date_time_lubridate >= mdy_hms(start_time),
         date_time_lubridate <= mdy_hms(end_time)) 

raw_voltages <- data.frame(rawdata$voltage_1_m_v,rawdata$voltage_2_m_v,rawdata$voltage_3_m_v,rawdata$voltage_4_m_v) %>% # create OMEGAS data frame with the raw voltages
  mutate(mv1=as.numeric(rawdata.voltage_1_m_v),
         mv2=as.numeric(rawdata.voltage_2_m_v),
         mv3=as.numeric(rawdata.voltage_3_m_v),
         mv4=as.numeric(rawdata.voltage_4_m_v)) %>% # changing data to numeric arguments
  select(mv1, mv2, mv3, mv4) # cleaning data frame

omegas_temp_raw <- raw_voltages %>% # create OMEGAS data frame with the raw voltages
  mutate(v1=(mv1/1000),
         v2=(mv2/1000),
         v3=(mv3/1000),
         v4=(mv4/1000)) %>% # converting the mV to volts
  mutate(vbattery=((v2/100)*101.57)) %>% # calculate vbattery
  mutate(z=(v4/100)+vbattery*((15000*1.01)/((1000000*1.01)+(15000*1.01)))) %>% # calculate column k
  mutate(y=(z*(1000000*1.01))) %>% # calculate column l
  mutate(rthermistor=(y/(vbattery-z))) %>% # calculate Rthermistor
  mutate(sh_a=as.numeric(0.00106329736674527)) %>% # create column with Steinhart constant A
  mutate(sh_b=as.numeric(0.000251377462346306)) %>% # create column with Steinhart constant B
  mutate(sh_c=as.numeric(2.55455247726963E-08)) %>% # create column with Steinhart constant C
  mutate(k=(1/(sh_a+sh_b*log(rthermistor)+sh_c*(log(rthermistor))^3))) %>% # create column to calculate intermediate value K
  mutate(durafet=as.numeric((k-273.15))) %>% # create new column to calculate durafet therm 
  mutate(calt=as.numeric(1.0086*durafet+0.3157)) # create Cal_T column (does not get used for further calibration)

temp <- c(omegas_temp_raw$durafet) # copy durafet therm into tris pH template
b <- as.numeric(rep("11911.08",length(temp))) # create vector for tris pH template column b
c <- as.numeric(rep("18.2499",length(temp))) # create vector for tris pH template column c
d <- as.numeric(rep("0.039336",length(temp))) # create vector for tris pH template column d
e <- as.numeric(rep("366.27059",length(temp))) # create vector for tris pH template column e
f <- as.numeric(rep("0.53993607",length(temp))) # create vector for tris pH template column f
g <- as.numeric(rep("0.00016329",length(temp))) # create vector for tris pH template column g
h <- as.numeric(rep("64.52243",length(temp))) # create vector for tris pH template column h
i <- as.numeric(rep("0.084041",length(temp))) # create vector for tris pH template column i
j <- as.numeric(rep("0.11149858",length(temp))) # create vector for tris pH template column j
k <- as.numeric(rep("273.15",length(temp))) # create vector for tris pH template column k
t <- as.numeric(rep(k+temp),length(temp)) # create vector for tris pH template column t
m <- as.numeric(rep("35",length(temp))) # create vector for tris pH template column m

raw_tris_ph <- data.frame(temp,b,c,d,e,f,g,h,i,j,t,k,m) %>% # create tris pH template as a data frame with all above columns
  mutate(n=(b-(c*m)-(d*m*m))*1/t) %>% # create column n
  mutate(o=(-e+(f*m)+(g*m*m))) %>% # create column o
  mutate(p=(h-(i*m))*log(t)-(j*(t))) %>% # create column p
  mutate(trisph=(n+o+p)) # calculate tris pH, add as a new column to tris pH template data frame

omegas_ph_raw <- data.frame(rawdata$date_lubridate,rawdata$time_lubridate,rawdata$date_time_lubridate,omegas_temp_raw$durafet,omegas_temp_raw$v1) %>% # create data frame with durafet therm and voltage 1 values
  rename(date_time=rawdata.date_time_lubridate,
         date=rawdata.date_lubridate,
         time=rawdata.time_lubridate) %>% # rename date/time column from trisdata data frame
  mutate(trisph=raw_tris_ph$trisph) %>% # add tris pH values into calibration dataframe TRIS PH IS NOT THE SAME LENGTH AS THE RAW DATA
  mutate(tk=omegas_temp_raw$durafet+273.15) %>% # add TK column to data frame
  mutate(st=(8.31451*tk/96487*log(10))) %>% # add S(T) column to data frame
  mutate(eo=((calibration_values$v1)-(calibration_values$trisph)*8.31451*(273.15+calibration_values$durafet_temp)*log(10)/96487)) %>% # calculate eo value using calibration values
  mutate(eot=(eo-(0.001*(tk-(273.15+calibration_values$durafet_temp))))) %>% # add Eo(T) column to data frame
  mutate(omegasrawph=(omegas_temp_raw$v1-eot)/st) %>% # add pH column to data frame
  mutate(diff=(trisph-omegasrawph)) # add difference column (tris pH - omegas pH) to data frame

raw_calibrated <- omegas_ph_raw %>% # create new dataframe using omegasph_raw data
  select(date_time, omegas_temp_raw.durafet, omegasrawph) %>% # keep only date/time, temperature, and pH columns
  rename("durafet_temp"=2,
         "p_h"=3)

#unique identifier for final calibrated data
raw_calibrated_plus1 <- raw_calibrated %>%
  mutate(logger = "madgetech",
         tolerance = "+1")

#Write .csv
write.csv(raw_calibrated_plus1, here("data", "calibrated", paste(filename_raw,"_omegas_plus1.csv", sep="")),row.names = FALSE) # create csv with calibrated values
```

## Run -1 tolerance calibration for Madgetech deployment data
```{r}
#load calibration data
calibration_values <- read_csv(here("data", "calibrated", paste(filename_tris,"_omegas_minus1_calib.csv",sep=""))) # read in tris data excel file

rawdata <- read_csv(here("data", "raw", paste(filename_raw,".csv",sep=""))) %>% # read in tris data excel file
  filter(row_number()!=c(1:5)) %>% # remove the first 5 rows
  row_to_names(row_number=1) %>% # make the top row the column headers
  rename("Date"=1,
         "Time"=2) %>% # rename date and time columns
  clean_names() %>% # clean up column header names
  mutate(date_lubridate=mdy(date)) %>% # tell R "date" is a DATE
  mutate(time_lubridate=hms(time)) %>% # tell R "time" is a TIME
  unite(date_time, c(date, time), sep = " ", remove = TRUE) %>% # combine the date and time columns
  mutate(date_time_lubridate=mdy_hms(date_time)) %>% # tell R "date_time" is a DATE and a TIME
  arrange(date_time_lubridate) %>%
  filter(date_time_lubridate >= mdy_hms(start_time),
         date_time_lubridate <= mdy_hms(end_time)) 

raw_voltages <- data.frame(rawdata$voltage_1_m_v,rawdata$voltage_2_m_v,rawdata$voltage_3_m_v,rawdata$voltage_4_m_v) %>% # create OMEGAS data frame with the raw voltages
  mutate(mv1=as.numeric(rawdata.voltage_1_m_v),
         mv2=as.numeric(rawdata.voltage_2_m_v),
         mv3=as.numeric(rawdata.voltage_3_m_v),
         mv4=as.numeric(rawdata.voltage_4_m_v)) %>% # changing data to numeric arguments
  select(mv1, mv2, mv3, mv4) # cleaning data frame

omegas_temp_raw <- raw_voltages %>% # create OMEGAS data frame with the raw voltages
  mutate(v1=(mv1/1000),
         v2=(mv2/1000),
         v3=(mv3/1000),
         v4=(mv4/1000)) %>% # converting the mV to volts
  mutate(vbattery=((v2/100)*101.57)) %>% # calculate vbattery
  mutate(z=(v4/100)+vbattery*((15000*0.99)/((1000000*0.99)+(15000*0.99)))) %>% # calculate column k
  mutate(y=(z*(1000000*0.99))) %>% # calculate column l
  mutate(rthermistor=(y/(vbattery-z))) %>% # calculate Rthermistor
  mutate(sh_a=as.numeric(0.00106329736674527)) %>% # create column with Steinhart constant A
  mutate(sh_b=as.numeric(0.000251377462346306)) %>% # create column with Steinhart constant B
  mutate(sh_c=as.numeric(2.55455247726963E-08)) %>% # create column with Steinhart constant C
  mutate(k=(1/(sh_a+sh_b*log(rthermistor)+sh_c*(log(rthermistor))^3))) %>% # create column to calculate intermediate value K
  mutate(durafet=as.numeric((k-273.15))) %>% # create new column to calculate durafet therm 
  mutate(calt=as.numeric(1.0086*durafet+0.3157)) # create Cal_T column (does not get used for further calibration)

temp <- c(omegas_temp_raw$durafet) # copy durafet therm into tris pH template
b <- as.numeric(rep("11911.08",length(temp))) # create vector for tris pH template column b
c <- as.numeric(rep("18.2499",length(temp))) # create vector for tris pH template column c
d <- as.numeric(rep("0.039336",length(temp))) # create vector for tris pH template column d
e <- as.numeric(rep("366.27059",length(temp))) # create vector for tris pH template column e
f <- as.numeric(rep("0.53993607",length(temp))) # create vector for tris pH template column f
g <- as.numeric(rep("0.00016329",length(temp))) # create vector for tris pH template column g
h <- as.numeric(rep("64.52243",length(temp))) # create vector for tris pH template column h
i <- as.numeric(rep("0.084041",length(temp))) # create vector for tris pH template column i
j <- as.numeric(rep("0.11149858",length(temp))) # create vector for tris pH template column j
k <- as.numeric(rep("273.15",length(temp))) # create vector for tris pH template column k
t <- as.numeric(rep(k+temp),length(temp)) # create vector for tris pH template column t
m <- as.numeric(rep("35",length(temp))) # create vector for tris pH template column m

raw_tris_ph <- data.frame(temp,b,c,d,e,f,g,h,i,j,t,k,m) %>% # create tris pH template as a data frame with all above columns
  mutate(n=(b-(c*m)-(d*m*m))*1/t) %>% # create column n
  mutate(o=(-e+(f*m)+(g*m*m))) %>% # create column o
  mutate(p=(h-(i*m))*log(t)-(j*(t))) %>% # create column p
  mutate(trisph=(n+o+p)) # calculate tris pH, add as a new column to tris pH template data frame

omegas_ph_raw <- data.frame(rawdata$date_lubridate,rawdata$time_lubridate,rawdata$date_time_lubridate,omegas_temp_raw$durafet,omegas_temp_raw$v1) %>% # create data frame with durafet therm and voltage 1 values
  rename(date_time=rawdata.date_time_lubridate,
         date=rawdata.date_lubridate,
         time=rawdata.time_lubridate) %>% # rename date/time column from trisdata data frame
  mutate(trisph=raw_tris_ph$trisph) %>% # add tris pH values into calibration dataframe TRIS PH IS NOT THE SAME LENGTH AS THE RAW DATA
  mutate(tk=omegas_temp_raw$durafet+273.15) %>% # add TK column to data frame
  mutate(st=(8.31451*tk/96487*log(10))) %>% # add S(T) column to data frame
  mutate(eo=((calibration_values$v1)-(calibration_values$trisph)*8.31451*(273.15+calibration_values$durafet_temp)*log(10)/96487)) %>% # calculate eo value using calibration values
  mutate(eot=(eo-(0.001*(tk-(273.15+calibration_values$durafet_temp))))) %>% # add Eo(T) column to data frame
  mutate(omegasrawph=(omegas_temp_raw$v1-eot)/st) %>% # add pH column to data frame
  mutate(diff=(trisph-omegasrawph)) # add difference column (tris pH - omegas pH) to data frame

raw_calibrated <- omegas_ph_raw %>% # create new dataframe using omegasph_raw data
  select(date_time, omegas_temp_raw.durafet, omegasrawph) %>% # keep only date/time, temperature, and pH columns
  rename("durafet_temp"=2,
         "p_h"=3)

#unique identifier for final calibrated data
raw_calibrated_minus1 <- raw_calibrated %>%
  mutate(logger = "madgetech",
         tolerance = "-1")

#Write .csv
write.csv(raw_calibrated_minus1, here("data", "calibrated", paste(filename_raw,"_omegas_minus1.csv", sep="")), row.names = FALSE) # create csv with calibrated values
```