---
title: "compare madgetech and arduino reads"
author: "Amelia Ritger"
date: "2022-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries
```{r}
library(tidyverse)
library(here)
library(lubridate)
```

MAKE SURE CALIBRATED FOLDER only has the files you want to analyze

Load sensor data
```{r}
files_all <- list.files(here("data", "calibrated"), pattern = ".csv$", recursive = FALSE, full.names = TRUE)

merged <- read_csv(files_all, col_names = TRUE) %>%
  select(1, 2, 12, 13)
```

Load deployment data
```{r}
files_dep <- list.files(here("data", "calibrated", "save"), pattern = ".csv$", recursive = FALSE, full.names = TRUE)

merged_dep <- read_csv(files_dep, col_names = TRUE) %>%
  select(1,2,4,5)

merged_all <- rbind(merged_dep, merged) %>%
  mutate(period=ifelse(date_time<=ymd_hms("2022-12-15 00:00:00"), "14",
                       ifelse(date_time>=ymd_hms("2022-12-16 14:00:00"), "16",
                              ifelse(date_time>ymd_hms("2022-12-15 13:00:00") & date_time<ymd_hms("2022-12-16 14:00:00"), "15dep", "15"))))

ggplot(merged_all, aes(x=date_time, y=durafet_temp, group=period)) +
  geom_point(aes(color=period))
```


```{r}
merge_comp <- merged_all %>%
  arrange(date_time) %>%
  group_by(period) %>%
  mutate(diff_time = date_time-lag(date_time, default = first(date_time)),
         diff_temp = durafet_temp-lag(durafet_temp, default=first(durafet_temp))) %>%
  filter(diff_temp > 0.05 | diff_temp < -0.05) %>%
  filter(!(date_time>=ymd_hms("2022-12-14 18:18:40") & date_time<=ymd_hms("2022-12-15 00:00:00"))) %>%
  group_by(period) %>%
  mutate(diff_time = date_time-lag(date_time, default = first(date_time)),
         diff_temp = durafet_temp-lag(durafet_temp, default=first(durafet_temp))) %>%
  filter(!diff_temp==0) %>%
  ungroup() %>%
  group_by(period,logger) %>%
  summarize(mean_diff = mean(diff_temp),
            mean_temp = mean(durafet_temp)) %>%
  mutate(mean_diff = ifelse(period==14, mean_diff*-1, mean_diff))
```


```{r}
library(ggpmisc)

logg <- merge_comp %>%
  filter(logger=="madgetech")

ggplot(logg, aes(x=mean_temp, y=mean_diff)) +
  geom_point() +
  stat_poly_line() +
  stat_poly_eq(aes(label = paste(after_stat(eq.label)))) +
  labs(x="Temperature", y="Avg temp difference between madgetech and arduino")

ggsave("madgetech-temp_all.png")
```

