---
title: "STEP 3: Apply GREEN and RED calibration data to all readings"
author: "Amelia Ritger"
date: "2023-04-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load libraries, set constants
```{r}
library(tidyverse)
library(readr)
library(janitor)
library(here)
library(lubridate)

#Tris calibration values
ard_filename_red_tris <-  "CLEAN_red_ard_20_omegas_calib"#"CLEAN_red_mad_overnight_omegas_calib" 
mad_filename_red_tris <-  "CLEAN_red_ard_20_omegas_calib"#"CLEAN_red_mad_overnight_omegas_calib"

ard_filename_green_tris <- "CLEAN_green_mad_20_omegas_calib" #"CLEAN_green_mad_overnight_omegas_calib"
mad_filename_green_tris <- "CLEAN_green_mad_20_omegas_calib" #"CLEAN_green_mad_overnight_omegas_calib"

#apply temperature correction equations to each durafet (ARDUINO)
ard_temp_corr_green_m <- 1+0.0673 
ard_temp_corr_green_b <- -0.335
ard_temp_corr_red_m   <- 1+0.0913 
ard_temp_corr_red_b   <- 0.264

#apply temperature correction equations to each durafet (MADGETECH)
mad_temp_corr_green_m <- 1-0.011
mad_temp_corr_green_b <- 0.626
mad_temp_corr_red_m   <- 1-0.0185
mad_temp_corr_red_b   <- 0.405

phvar <-   0#-0.111
tempvar <- 0#-0.041

#calculated uncertainties using raw data
var_ard <- 0 #calculated uncertainties using raw data
var_ard_real <- 0 #calculated uncertainties using raw data
var_madg <- 0 #calculated uncertainties using raw data

madg_correction_m <- 1 #slope coefficient for madgetech (corrected with HOBO)
madg_correction_b <- 0
ard_correction_m <- 1 #slope coefficient for arduino (corrected with HOBO)
ard_correction_b <- 0
```

## Run calibration for GREEN data
```{r}
pathname <- "../data/CLEAN/" #name the file pathway

file_names <- list.files(path = pathname, 
                         full.names = F,
                         pattern="green")

for (file_name in file_names){
  file.temp <- read_csv(paste0(pathname, file_name))
  assign(gsub(".csv", "", file_name, fixed = T), file.temp)

  calibration_values <- read_csv(here("data", "calibrated", paste(ifelse(str_detect(file_name, "ard"), ard_filename_green_tris, mad_filename_green_tris),".csv",sep=""))) # read in tris data excel file
  
  rawdata <- file.temp %>%
    mutate(date_time_lubridate=ymd_hms(date_time)) # tell R "date_time" is a DATE and a TIME

raw_voltages <- data.frame(rawdata$v1,rawdata$v2,rawdata$v3,rawdata$v4) %>% # create OMEGAS data frame with the raw voltages
  mutate(mv1=as.numeric(rawdata.v1) + phvar,
         mv2=as.numeric(rawdata.v2),
         mv3=as.numeric(rawdata.v3),
         mv4=as.numeric(rawdata.v4) + tempvar) %>% # changing data to numeric arguments
  select(mv1, mv2, mv3, mv4) # cleaning data frame

omegas_temp_raw <- raw_voltages %>% # create OMEGAS data frame with the raw voltages
  mutate(v1=(mv1/1000),
         v2=(mv2/1000),
         v3=(mv3/1000),
         v4=(mv4/1000)) %>% # converting the mV to volts
  mutate(vbattery=((v2/100)*101.57)) %>% # calculate vbattery
  mutate(z=(v4/100)+vbattery*((15000*1)/((1000000*1)+(15000*1)))) %>% # calculate column k
  mutate(y=(z*(1000000*1))) %>% # calculate column l
  mutate(rthermistor=(y/(vbattery-z))) %>% # calculate Rthermistor
  mutate(sh_a=as.numeric(0.00106329736674527)) %>% # create column with Steinhart constant A
  mutate(sh_b=as.numeric(0.000251377462346306)) %>% # create column with Steinhart constant B
  mutate(sh_c=as.numeric(2.55455247726963E-08)) %>% # create column with Steinhart constant C
  mutate(k=(1/(sh_a+sh_b*log(rthermistor)+sh_c*(log(rthermistor))^3))) %>% # create column to calculate intermediate value K
  mutate(durafet=as.numeric((k-273.15))) %>% # create new column to calculate durafet therm
  mutate(durafet=durafet*ifelse(str_detect(file_name, "ard"), ard_temp_corr_green_m, mad_temp_corr_green_m) + ifelse(str_detect(file_name, "ard"), ard_temp_corr_green_b,mad_temp_corr_green_b)) # do temperature correction
  #mutate(durafet=((durafet*madg_correction_m)-madg_correction_b)) %>% #do temperature correction
  #mutate(durafet=(durafet+var_madg)) #correct with calculated uncertainties

temp <- c(omegas_temp_raw$durafet) # copy durafet therm into tris pH template
b <- as.numeric(rep("11911.08",length(temp))) # create vector for tris pH template column b
c <- as.numeric(rep("18.2499",length(temp))) # create vector for tris pH template column c
d <- as.numeric(rep("0.039336",length(temp))) # create vector for tris pH template column d
e <- as.numeric(rep("366.27059",length(temp))) # create vector for tris pH template column e
f <- as.numeric(rep("0.53993607",length(temp))) # create vector for tris pH template column f
g <- as.numeric(rep("0.00016329",length(temp))) # create vector for tris pH template column g
h <- as.numeric(rep("64.52243",length(temp))) # create vector for tris pH template column h
i <- as.numeric(rep("0.084041",length(temp))) # create vector for tris pH template column i
j <- as.numeric(rep("0.11149858",length(temp))) # create vector for tris pH template column j
k <- as.numeric(rep("273.15",length(temp))) # create vector for tris pH template column k
t <- as.numeric(rep(k+temp),length(temp)) # create vector for tris pH template column t
m <- as.numeric(rep("35",length(temp))) # create vector for tris pH template column m

raw_tris_ph <- data.frame(temp,b,c,d,e,f,g,h,i,j,t,k,m) %>% # create tris pH template as a data frame with all above columns
  mutate(n=(b-(c*m)-(d*m*m))*1/t) %>% # create column n
  mutate(o=(-e+(f*m)+(g*m*m))) %>% # create column o
  mutate(p=(h-(i*m))*log(t)-(j*(t))) %>% # create column p
  mutate(trisph=(n+o+p)) # calculate tris pH, add as a new column to tris pH template data frame

omegas_ph_raw <- data.frame(rawdata$date_time,omegas_temp_raw$durafet,omegas_temp_raw$v1) %>%
   # create data frame with durafet therm and voltage 1 values
  rename(date_time=rawdata.date_time) %>% # rename date/time column from trisdata data frame
  mutate(trisph=raw_tris_ph$trisph) %>% # add tris pH values into calibration dataframe TRIS PH IS NOT THE SAME LENGTH AS THE RAW DATA
  mutate(tk=omegas_temp_raw$durafet+273.15) %>% # add TK column to data frame
  mutate(st=(8.31451*tk/96487*log(10))) %>% # add S(T) column to data frame
  mutate(eo=((calibration_values$v1)-(calibration_values$trisph)*8.31451*(273.15+calibration_values$durafet_temp)*log(10)/96487)) %>% # calculate eo value using calibration values
  mutate(eot=(eo-(0.001*(tk-(273.15+calibration_values$durafet_temp))))) %>% # add Eo(T) column to data frame
  mutate(omegasrawph=(omegas_temp_raw$v1-eot)/st) %>% # add pH column to data frame
  mutate(diff=(trisph-omegasrawph)) # add difference column (tris pH - omegas pH) to data frame

raw_calibrated <- omegas_ph_raw %>% # create new dataframe using omegasph_raw data
  select(date_time, omegas_temp_raw.durafet, omegasrawph) %>% # keep only date/time, temperature, and pH columns
  rename("p_h"=3) %>%
  mutate(logger = rawdata$logger,
         durafet = rawdata$durafet)

#Write .csv
write.csv(raw_calibrated, here("data", "calibrated", paste("OMEGAS_",file_name, sep="")),row.names = FALSE) # create csv with calibrated values
}
```

## Run calibration for RED data
```{r}
pathname <- "../data/CLEAN/" #name the file pathway

file_names <- list.files(path = pathname, 
                         full.names = F,
                         pattern="red")

for (file_name in file_names){
  file.temp <- read_csv(paste0(pathname, file_name))
  assign(gsub(".csv", "", file_name, fixed = T), file.temp)
  
  calibration_values <- read_csv(here("data", "calibrated", paste(ifelse(str_detect(file_name, "ard"), ard_filename_red_tris, mad_filename_red_tris),".csv",sep=""))) # read in tris data excel file
  
  rawdata <- file.temp %>%
    mutate(date_time_lubridate=ymd_hms(date_time)) # tell R "date_time" is a DATE and a TIME
  
raw_voltages <- data.frame(rawdata$v1,rawdata$v2,rawdata$v3,rawdata$v4) %>% # create OMEGAS data frame with the raw voltages
  mutate(mv1=as.numeric(rawdata.v1) + phvar,
         mv2=as.numeric(rawdata.v2),
         mv3=as.numeric(rawdata.v3),
         mv4=as.numeric(rawdata.v4) + tempvar) %>% # changing data to numeric arguments
  select(mv1, mv2, mv3, mv4) # cleaning data frame

omegas_temp_raw <- raw_voltages %>% # create OMEGAS data frame with the raw voltages
  mutate(v1=(mv1/1000),
         v2=(mv2/1000),
         v3=(mv3/1000),
         v4=(mv4/1000)) %>% # converting the mV to volts
  mutate(vbattery=((v2/100)*101.57)) %>% # calculate vbattery
  mutate(z=(v4/100)+vbattery*((15000*1)/((1000000*1)+(15000*1)))) %>% # calculate column k
  mutate(y=(z*(1000000*1))) %>% # calculate column l
  mutate(rthermistor=(y/(vbattery-z))) %>% # calculate Rthermistor
  mutate(sh_a=as.numeric(0.00106329736674527)) %>% # create column with Steinhart constant A
  mutate(sh_b=as.numeric(0.000251377462346306)) %>% # create column with Steinhart constant B
  mutate(sh_c=as.numeric(2.55455247726963E-08)) %>% # create column with Steinhart constant C
  mutate(k=(1/(sh_a+sh_b*log(rthermistor)+sh_c*(log(rthermistor))^3))) %>% # create column to calculate intermediate value K
  mutate(durafet=as.numeric((k-273.15))) %>% # create new column to calculate durafet therm
  mutate(durafet=durafet*ifelse(str_detect(file_name, "ard"), ard_temp_corr_red_m, mad_temp_corr_red_m) + ifelse(str_detect(file_name, "ard"), ard_temp_corr_red_b,mad_temp_corr_red_b)) %>% # do temperature correction
  mutate(durafet=(durafet+var_madg)) #correct with calculated uncertainties

temp <- c(omegas_temp_raw$durafet) # copy durafet therm into tris pH template
b <- as.numeric(rep("11911.08",length(temp))) # create vector for tris pH template column b
c <- as.numeric(rep("18.2499",length(temp))) # create vector for tris pH template column c
d <- as.numeric(rep("0.039336",length(temp))) # create vector for tris pH template column d
e <- as.numeric(rep("366.27059",length(temp))) # create vector for tris pH template column e
f <- as.numeric(rep("0.53993607",length(temp))) # create vector for tris pH template column f
g <- as.numeric(rep("0.00016329",length(temp))) # create vector for tris pH template column g
h <- as.numeric(rep("64.52243",length(temp))) # create vector for tris pH template column h
i <- as.numeric(rep("0.084041",length(temp))) # create vector for tris pH template column i
j <- as.numeric(rep("0.11149858",length(temp))) # create vector for tris pH template column j
k <- as.numeric(rep("273.15",length(temp))) # create vector for tris pH template column k
t <- as.numeric(rep(k+temp),length(temp)) # create vector for tris pH template column t
m <- as.numeric(rep("35",length(temp))) # create vector for tris pH template column m

raw_tris_ph <- data.frame(temp,b,c,d,e,f,g,h,i,j,t,k,m) %>% # create tris pH template as a data frame with all above columns
  mutate(n=(b-(c*m)-(d*m*m))*1/t) %>% # create column n
  mutate(o=(-e+(f*m)+(g*m*m))) %>% # create column o
  mutate(p=(h-(i*m))*log(t)-(j*(t))) %>% # create column p
  mutate(trisph=(n+o+p)) # calculate tris pH, add as a new column to tris pH template data frame

omegas_ph_raw <- data.frame(rawdata$date_time,omegas_temp_raw$durafet,omegas_temp_raw$v1) %>%
   # create data frame with durafet therm and voltage 1 values
  rename(date_time=rawdata.date_time) %>% # rename date/time column from trisdata data frame
  mutate(trisph=raw_tris_ph$trisph) %>% # add tris pH values into calibration dataframe TRIS PH IS NOT THE SAME LENGTH AS THE RAW DATA
  mutate(tk=omegas_temp_raw$durafet+273.15) %>% # add TK column to data frame
  mutate(st=(8.31451*tk/96487*log(10))) %>% # add S(T) column to data frame
  mutate(eo=((calibration_values$v1)-(calibration_values$trisph)*8.31451*(273.15+calibration_values$durafet_temp)*log(10)/96487)) %>% # calculate eo value using calibration values
  mutate(eot=(eo-(0.001*(tk-(273.15+calibration_values$durafet_temp))))) %>% # add Eo(T) column to data frame
  mutate(omegasrawph=(omegas_temp_raw$v1-eot)/st) %>% # add pH column to data frame
  mutate(diff=(trisph-omegasrawph)) # add difference column (tris pH - omegas pH) to data frame

raw_calibrated <- omegas_ph_raw %>% # create new dataframe using omegasph_raw data
  select(date_time, omegas_temp_raw.durafet, omegasrawph) %>% # keep only date/time, temperature, and pH columns
  rename("p_h"=3) %>%
  mutate(logger = rawdata$logger,
         durafet = rawdata$durafet)

#Write .csv
write.csv(raw_calibrated, here("data", "calibrated", paste("OMEGAS_",file_name, sep="")),row.names = FALSE) # create csv with calibrated values
}
```
