---
title: "STEP 2: Calculate Tris calibration constants for DuraFET"
author: "Amelia Ritger"
date: "2024-01-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load libraries, set constants
```{r}
library(tidyverse)
library(readr)
library(janitor)
library(here)
library(lubridate)

filename <- "0125tris_clean" #filename for tris data
row_remove <- 15 # number of rows to remove from beginning of data frame
```

## Run "Ideal" calibration for DuraFET
```{r}
var_ard <- 0 #calculated uncertainties using raw data

ard_correction_m <- 1 #slope coefficient for arduino (corrected with HOBO)
ard_correction_b <- 0

trisdata <- read_csv(here("temp", "data", "jan2024", paste(filename,".csv",sep=""))) %>%
  mutate(date = mdy(date),
           time = hms(time),
           date_time = paste(date, time),
           date_time_lubridate=ymd_hms(date_time)) %>%
  select(date_time_lubridate, v1, v2, v3, v4) %>%
  rename(date_time = date_time_lubridate)

tris_voltages <- data.frame(trisdata$v1,trisdata$v2,trisdata$v3,trisdata$v4) %>% # create OMEGAS data frame with the raw voltages
  mutate(mv1=as.numeric(trisdata.v1),
         mv2=as.numeric(trisdata.v2),
         mv3=as.numeric(trisdata.v3),
         mv4=as.numeric(trisdata.v4)) %>% # changing data to numeric arguments
  select(mv1, mv2, mv3, mv4) # cleaning data frame

omegas_temp_tris <- tris_voltages %>% # create new data frame using omegas values
  mutate(v1=(mv1/1000),
         v2=(mv2/1000),
         v3=(mv3/1000),
         v4=(mv4/1000)) %>% # converting the mV to volts
  mutate(vbattery=((abs(v3)/100)*101.57)) %>% # calculate vbattery
  mutate(z=(v4/100)+vbattery*((15000*1)/((1000000*1)+(15000*1)))) %>% # calculate column k
  mutate(y=(z*(1000000*1))) %>% # calculate column l
  mutate(rthermistor=(y/(vbattery-z))) %>% # calculate Rthermistor
  mutate(sh_a=as.numeric(0.00106329736674527)) %>% # create column with Steinhart constant A
  mutate(sh_b=as.numeric(0.000251377462346306)) %>% # create column with Steinhart constant B
  mutate(sh_c=as.numeric(2.55455247726963E-08)) %>% # create column with Steinhart constant C
  mutate(k=(1/(sh_a+sh_b*log(rthermistor)+sh_c*(log(rthermistor))^3))) %>% # create column to calculate intermediate value K
  mutate(durafet=as.numeric((k-273.15))) %>% # create new column to calculate durafet therm
  mutate(calt=as.numeric(1.0086*durafet+0.3157)) # create Cal_T column (does not get used for further calibration)

temp <- c(omegas_temp_tris$durafet) # copy durafet therm into tris pH template
b <- as.numeric(rep("11911.08",length(temp))) # create vector for tris pH template column b
c <- as.numeric(rep("18.2499",length(temp))) # create vector for tris pH template column c
d <- as.numeric(rep("0.039336",length(temp))) # create vector for tris pH template column d
e <- as.numeric(rep("366.27059",length(temp))) # create vector for tris pH template column e
f <- as.numeric(rep("0.53993607",length(temp))) # create vector for tris pH template column f
g <- as.numeric(rep("0.00016329",length(temp))) # create vector for tris pH template column g
h <- as.numeric(rep("64.52243",length(temp))) # create vector for tris pH template column h
i <- as.numeric(rep("0.084041",length(temp))) # create vector for tris pH template column i
j <- as.numeric(rep("0.11149858",length(temp))) # create vector for tris pH template column j
k <- as.numeric(rep("273.15",length(temp))) # create vector for tris pH template column k
t <- as.numeric(rep(k+temp),length(temp)) # create vector for tris pH template column t
m <- as.numeric(rep("35",length(temp))) # create vector for tris pH template column m

tris_ph_template <- data.frame(temp,b,c,d,e,f,g,h,i,j,t,k,m)%>% # create tris pH template as a data frame with all above columns
  mutate(n=(b-(c*m)-(d*m*m))*1/t) %>% # create column n
  mutate(o=(-e+(f*m)+(g*m*m))) %>% # create column o
  mutate(p=(h-(i*m))*log(t)-(j*(t))) %>% # create column p
  mutate(trisph=(n+o+p)) # calculate tris pH, add as a new column to tris pH template data frame

omegas_ph_tris <- data.frame(trisdata$date_time,omegas_temp_tris$durafet,omegas_temp_tris$v1) %>% # create data frame with durafet therm and voltage 1 values
  mutate(trisph=tris_ph_template$trisph) %>% # add tris pH values into calibration dataframe 
  mutate(tk=omegas_temp_tris$durafet+273.15) %>% # add TK column to data frame
  mutate(st=(8.31451*tk/96487*log(10))) %>% # add S(T) column to data frame
  mutate(eot=(-0.374911706-(0.001*(tk-290.2751473)))) %>% # add Eo(T) column to data frame
  mutate(omegasph=(omegas_temp_tris$v1-eot)/st) %>% # add pH column to data frame
  mutate(diff=(trisph-omegasph)) %>% # add difference column (tris pH - omegas pH) to data frame
  mutate(tempdiff=abs(omegas_temp_tris.durafet-lag(omegas_temp_tris.durafet,n=5,default=first(omegas_temp_tris.durafet)))) %>% # find difference between two temp measurements 5 rows apart to identify where temperature stabilizes
  mutate(phdiff=abs(omegasph-lag(omegasph,n=5,default=first(omegasph)))) # find difference between two pH measurements 5 rows apart to identify where pH stabilizes

calibration_values <- omegas_ph_tris %>% # work in omegas_calibration dataframe
  filter(row_number()!=c(1:row_remove)) %>% # remove the first 100 rows (first 20 minutes of data)
  slice_min(tempdiff,n=10) %>% # select the rows that contains the minimum values of change in temperature over time 
  slice_min(phdiff,n=1) %>% # select the row that contains the minimum value of change in pH over time in within the 10 lowest temp differences
  mutate(diff_omegasph = (omegasph - mean(omegasph))) %>%
  slice_min(diff_omegasph) %>%
  slice(1L)

#Write out .csv files
write.csv(omegas_ph_tris, here("temp", "data", "jan2024", paste(filename,"_omegas.csv", sep="")),row.names = FALSE) # create csv with calibrated values
write.csv(calibration_values, here("temp", "data", "jan2024", paste(filename,"_omegas_calib.csv", sep="")),row.names=FALSE)
```
